huh_encore:
  js_entries:
    - name: "contao-tab-control-bundle"
      file: "vendor/heimrichhannot/contao-tab-control-bundle/src/Resources/assets/js/contao-tab-control-bundle.js"
  unset_global_keys:
    js:
      - 'huh_contao-tab-control-bundle_bootstrap-tabs'
      - 'huh_contao-tab-control-bundle'