services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\TabControlBundle\:
    resource: '../../{Asset,Command,Controller,DataContainer,EventListener,Helper}/*'

  HeimrichHannot\TabControlBundle\Asset\FrontendAsset:
    calls:
      - [ setEncoreFrontendAsset, [ '@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset' ] ]
